.\"	$OpenBSD: rpki-client.8,v 1.32 2020/10/23 20:37:11 jmc Exp $
.\"
.\" Copyright (c) 2019 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: November 15 2020 $
.Dt RKPIDUMP 8
.Os
.Sh NAME
.Nm rpkidump
.Nd Decoder utility for X.509 RPKI files
.Sh SYNOPSIS
.Nm
.Op Ar rpkifile
.Sh DESCRIPTION
The
.Nm
utility attempts to print the eContent field of a CMS encoded RPKI data file
in human readable format.
Additionally the
.Em certificate
contained within the CMS signed-data object is printed in
.Cm PEM
encoded format,
for easy inspection with the
.Xr openssl 1
utility.
.Pp
The
.Nm
utility can work with
.Em .roa ,
.Em .mft ,
and
.Em .cer
files.
.Sh SEE ALSO
.Xr rpki-client 8
.Sh STANDARDS
The following standards are used or referenced in
.Nm :
.Bl -tag -width -Ds
.It RFC 3370
Cryptographic Message Syntax (CMS) Algorithms.
.It RFC 3779
X.509 Extensions for IP Addresses and AS Identifiers.
.It RFC 4291
IP Version 6 Addressing Architecture.
.It RFC 4631
Classless Inter-domain Routing (CIDR): The Internet Address Assignment
and Aggregation Plan.
.It RFC 5280
Internet X.509 Public Key Infrastructure Certificate and Certificate
Revocation List (CRL) Profile.
.It RFC 5652
Cryptographic Message Syntax (CMS).
.It RFC 5781
The rsync URI Scheme.
.It RFC 5952
A Recommendation for IPv6 Address Text Representation.
.It RFC 6480
An Infrastructure to Support Secure Internet Routing.
.It RFC 6482
A Profile for Route Origin Authorizations (ROAs).
.It RFC 6485
The Profile for Algorithms and Key Sizes for Use in the Resource Public Key
Infrastructure (RPKI).
.It RFC 6486
Manifests for the Resource Public Key Infrastructure (RPKI).
.It RFC 6487
A Profile for X.509 PKIX Resource Certificates.
.It RFC 6488
Signed Object Template for the Resource Public Key Infrastructure
(RPKI).
.It RFC 7730
Resource Public Key Infrastructure (RPKI) Trust Anchor Locator.
.El
.\" .Sh HISTORY
.Sh AUTHORS
.An Job Snijders Aq Mt job@openbsd.org .
.Sh CAVEATS
The
.Nm
utlility makes no attempt whatsover to cryptographically validate anything.
.\" .Sh BUGS
